### ISSUE TITLE
Send messages error

### ISSUE THREAD

**Issue by Lisovq** [eremeyko/VKMailing#1]
Строка 29 возвращает список с двумя элементами(['', 'example_domain]) который используется в запросах ниже
https://github.com/eremeyko/VKMailing/blob/afea1c13d2ef85ccf7349c248d734e97323ed2aa/mailing.py#L29

И в инструкции на 30-ой строке условие никогда не выполнится т.к. ids это ссылка с началом https://vk.com/, а не id
https://github.com/eremeyko/VKMailing/blob/afea1c13d2ef85ccf7349c248d734e97323ed2aa/mailing.py#L30

**Comment by eremeyko** [comment]
Скрипт полностью переписывается. Эти ошибки там уже исправлены и отработаны
